# Generated by Django 2.1.5 on 2019-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cource_website',
            field=models.CharField(default='udemy', max_length=64),
        ),
    ]
