# Generated by Django 2.1.5 on 2019-01-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_cource_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
